version: '3.9'

services:
  webapi:
    image: ${DOCKER_REGISTRY-}webapi
    container_name: web_api_ddona
    restart: always
    depends_on: 
      - db_redis
    build:
      context: .
      dockerfile: WebApi/Dockerfile

  db_redis:
    image: redis
    container_name: redis_ddona
    restart: always
    command: redis-server --requirepass @xap3r --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - redis_volume:/data
  
volumes:
  redis_volume: